import type { Cluster, Insight } from "./types";

export const clusters: Cluster[] = [
  { slug: "gtm-strategy", name: "GTM Strategy", blurb: "Positioning, pricing, market entry and the decisions that come before the campaigns." },
  { slug: "demand-generation", name: "Demand Generation", blurb: "Outbound, ABM, social selling, events and content that produce meetings rather than metrics." },
  { slug: "revenue-intelligence", name: "Revenue Intelligence", blurb: "Data, intent, OSINT and research: knowing who is in-market and why." },
  { slug: "ai-in-gtm", name: "AI in GTM", blurb: "What agents can actually do in go-to-market today, how to build them, and where humans still win." },
];

export const insights: Insight[] = [
  {
    slug: "demand-generation-2026-what-changed",
    title: "Demand generation in 2026: what changed and how to succeed",
    dek: "The buyer moved, the channels decayed, and the tooling got smarter. A practical account of what still works and what to stop paying for.",
    cluster: "demand-generation",
    author: "kingshuk-hazra",
    date: "2026-07-14",
    body: [
      "Every year someone declares outbound dead, and every year the companies that do it well keep growing. What actually died is the version of outbound where a list, a template and a sequencing tool were the whole strategy. This piece is about what replaced it.",
      "## Three things that changed",
      "First, buyers now complete most of the evaluation before they will speak to a vendor. Analyst firms have been saying this for a decade; the difference is that AI search has made it true for even small purchases. If your first touch is a demo request, you are meeting the buyer at the end of their process, not the start.",
      "Second, reply rates on template sequences collapsed. Deliverability tightened, inboxes filter harder, and buyers can now recognise a mail-merge from the subject line. The messages that still get replies read like they were written by one person to another after twenty minutes of research. Because they were.",
      "Third, the research and the writing became cheap. An agent can build an account brief in minutes and draft a message that references it. The scarce resource is no longer effort; it is judgement about which accounts deserve the effort.",
      "## What we do differently now",
      "- We build the account universe before the messaging. Fit and signal ranking decide who gets touched at all.",
      "- We write per persona from customer interviews, then let agents personalise per account from research. The system is human-designed and machine-executed.",
      "- We run social selling from real leaders' profiles, because a comment from a CTO still outperforms a sequence from an SDR.",
      "- We report meetings held and opportunities created. Opens and clicks are diagnostic, not outcomes.",
      "## What to stop paying for",
      "Purchased lists without a maintenance plan. Intent data that is not tuned to your closed-won history. Any vendor whose weekly report does not contain the word 'meeting'. And, increasingly, SDR headcount whose day is seventy percent research and data entry. That part has been automated; the twenty minutes of judgement has not.",
      "The winners in 2026 are not doing more outbound. They are doing less, to better accounts, with more relevance, and letting software carry the repetition.",
    ],
    related: ["social-selling-is-a-research-problem", "what-an-ai-sdr-does-all-day"],
  },
  {
    slug: "social-selling-is-a-research-problem",
    title: "Social selling is a research problem, not a content problem",
    dek: "Most LinkedIn programmes fail because they start with what the executive wants to say. The ones that work start with what the prospect has already said.",
    cluster: "demand-generation",
    author: "kingshuk-hazra",
    date: "2026-05-02",
    body: [
      "We have run social-selling programmes from executive profiles in healthcare, document software, software testing and media. The pattern that separates the ones that produced pipeline from the ones that produced likes is not writing quality. It is research.",
      "## The failure mode",
      "A founder agrees to post twice a week. An agency writes thoughtful pieces about the industry. Engagement grows among peers and vendors. Six months later, nobody can name a deal that came from it. The programme was broadcasting, and buyers do not respond to broadcasts, however good.",
      "## The working model",
      "Start with the target account list, not the content calendar. For each account, know who the buying group is and what they have said publicly: their posts, their comments, the roles they are hiring, what their CEO told an interviewer. Then engage with that. A comment that references a prospect's own argument is worth more than any post.",
      "Content still matters, but its job is different: it is the thing a prospect finds when they check your profile after you commented on theirs. It should answer the question they are already asking, which you know because you did the research.",
      "## Where agents fit",
      "This is exactly the kind of work agents are good at: monitoring hundreds of profiles for triggers, summarising what a prospect has said, drafting a comment for approval. The human still decides what to say. The machine makes sure they never miss the moment to say it.",
    ],
    related: ["demand-generation-2026-what-changed", "osint-for-sales-teams"],
  },
  {
    slug: "positioning-is-a-pricing-decision",
    title: "Positioning is a pricing decision",
    dek: "If your positioning does not change what you can charge, it is a tagline. A framework for positioning that shows up in the contract value.",
    cluster: "gtm-strategy",
    author: "kingshuk-hazra",
    date: "2026-03-18",
    body: [
      "The fastest test of a positioning statement is to ask what it lets you charge. If the answer is 'the same as before', the exercise produced a slogan. Positioning that works changes the comparison set in the buyer's head, and the comparison set determines the price.",
      "## The comparison set",
      "A buyer prices you against whatever they think you replace. If a compliance-automation vendor is compared to a spreadsheet, it is worth a few thousand dollars. Compared to a failed enterprise deal, it is worth a great deal more. The positioning work is choosing which comparison you want and earning the right to it.",
      "## A working sequence",
      "- Name the alternative. Not a competitor's brand; the thing the buyer does today. Spreadsheets, an intern, a consultant, doing nothing.",
      "- Name the cost of the alternative in the buyer's units: deals lost, weeks delayed, audits failed.",
      "- Name the one capability that removes that cost, and prove it with a number from a customer.",
      "- Only then, name the category. Categories are labels for comparison sets; pick the one where your price makes sense.",
      "## What this looks like in practice",
      "We ran this with a cloud partner entering India that arrived with eleven service lines. Eleven services means eleven comparison sets and no price. One wedge, cost-optimisation-led migration, anchored to a public benchmark, gave the sales team a number to talk about and a reason to be paid more than the incumbent integrators.",
      "Positioning is not what you say about yourself. It is the comparison you make the buyer draw, and the price that follows from it.",
    ],
    related: ["india-gtm-entry-playbook"],
  },
  {
    slug: "india-gtm-entry-playbook",
    title: "The India GTM entry playbook for global SaaS",
    dek: "What transfers from your home market, what does not, and the three mistakes we see on nearly every first attempt.",
    cluster: "gtm-strategy",
    author: "kingshuk-hazra",
    date: "2026-01-22",
    body: [
      "Between us, the founders spent years running India marketing for global technology vendors. The same three mistakes appear on almost every SaaS company's first attempt at the market, and each is avoidable.",
      "## Mistake one: pricing in dollars and hoping",
      "Indian mid-market buyers are sophisticated about value and ruthless about currency. A US price list converted at spot rate signals that you have not thought about the market. The companies that win either package differently for India or lead with a wedge whose ROI is obvious in rupees.",
      "## Mistake two: hiring a country manager before there is a motion",
      "A senior hire with a global title and no playbook will spend a year building relationships and a second year explaining why they have not converted. Build the motion first, with a small outsourced team if necessary, then hire the person who will scale what already works.",
      "## Mistake three: assuming your proof travels",
      "Logos from Fortune 500 companies impress in the US. In India, a buyer wants to know who in their sector, in their city, already trusts you. The first two Indian reference customers are worth more than the whole global logo wall, which means the first two deals should be chosen for reference value, not size.",
      "## What does transfer",
      "Your positioning, if it is about a problem rather than a feature. Your content, if it is translated into the buyer's context. Your product-led motion, if you have one, because Indian developers adopt fast. And your operating rhythm, if you bring it with you rather than waiting for the local team to invent one.",
    ],
    related: ["positioning-is-a-pricing-decision"],
  },
  {
    slug: "intent-data-is-not-a-list",
    title: "Intent data is not a list",
    dek: "Why most intent programmes produce the same accounts as everyone else's, and how to tune one to your own history so it stops.",
    cluster: "revenue-intelligence",
    author: "kingshuk-hazra",
    date: "2025-11-06",
    body: [
      "Buy an intent feed, filter for your category's topics, and you will get a list of accounts that are researching your category. So will your competitors, from the same vendor, on the same day. The feed is a commodity. The advantage is what you do to it.",
      "## What intent actually tells you",
      "Third-party intent is a probability, not a fact: an account has consumed content on a topic more than usual. It says nothing about fit, budget, timing or whether the person reading is the buyer or an intern. Used alone, it produces a large list of accounts you will chase and mostly lose.",
      "## Tuning to your own history",
      "The fix is to weight signals by how they correlated with your closed-won deals. For one client, funding rounds mattered far more than content consumption; for another, a specific job posting predicted a deal better than anything in the intent feed. This is a small modelling exercise on your CRM data, and it is the difference between a feed and a forecast.",
      "## Adding what vendors cannot see",
      "Public triggers, such as leadership changes, hiring, tech migrations, regulatory filings and conference talks, are visible to anyone who looks. Almost nobody looks systematically. Combined with fit and tuned intent, they produce the ranked weekly list that our clients' reps actually work from.",
      "A list tells you who exists. An intelligence feed tells you who to call this week and what to say. Only one of those is worth paying for.",
    ],
    related: ["osint-for-sales-teams", "what-an-ai-sdr-does-all-day"],
  },
  {
    slug: "osint-for-sales-teams",
    title: "OSINT for sales teams: a field guide",
    dek: "Open-source intelligence started in security and journalism. Applied to accounts, it is the most under-used advantage in B2B sales.",
    cluster: "revenue-intelligence",
    author: "kingshuk-hazra",
    date: "2025-09-10",
    body: [
      "Open-source intelligence is the discipline of building a reliable picture from public information. Security teams use it to profile threats; journalists use it to check claims. Sales teams mostly do not use it at all, which is a shame, because the account you are about to call has told the internet almost everything you need to know.",
      "## What is public",
      "- Hiring: job postings reveal priorities, tooling, budgets and the pain the new hire is meant to fix.",
      "- Filings and results: for listed companies, what the CEO promised investors and what the CFO is worried about.",
      "- Technology: detectable stacks, migrations, integrations and the vendors they have publicly thanked or blamed.",
      "- People: who joined, who left, who got promoted, what they said on stage or in a podcast.",
      "- Commitments: regulatory deadlines, sustainability targets, product launches announced with dates.",
      "## Turning it into a brief",
      "A useful OSINT brief is two pages: the account's stated priorities, the evidence, the buying group, the likely objection, and the one angle that connects your offer to a commitment they have already made. It takes an analyst three to four hours. It takes an agent, properly configured, about four minutes, and then a human ten minutes to check.",
      "## The rule",
      "Never reference anything the prospect would be surprised you know. The brief is for relevance, not for showing off. If the angle is right, you never need to say where it came from.",
    ],
    related: ["intent-data-is-not-a-list", "social-selling-is-a-research-problem"],
  },
  {
    slug: "what-an-ai-sdr-does-all-day",
    title: "What an AI SDR actually does all day",
    dek: "An honest hour-by-hour account of a production agent working a B2B pipeline, including the parts where it asks a human.",
    cluster: "ai-in-gtm",
    author: "kingshuk-hazra",
    date: "2026-06-09",
    body: [
      "There is a lot of marketing about AI SDRs and very little description. Here is what a set of agents we run actually does across a working day for a mid-market SaaS client, with the human touch-points left in.",
      "## 06:00: Universe refresh",
      "The prospecting agent re-scores the account universe against overnight signals: new job postings, funding announcements, leadership changes, website changes on tier-1 accounts. Fourteen accounts move into the active tier; six drop out.",
      "## 06:30: Research",
      "For each newly active account, the research agent builds a brief: what changed, who the buying group is, what they have said publicly, and the angle. Two accounts are flagged for human review because the signal is ambiguous.",
      "## 08:00: Qualification",
      "The qualification agent applies the client's rules (segment, size, stack, region, exclusions) and the tuned fit model. Nine of fourteen pass. The five that fail are logged with reasons so the rules can be reviewed.",
      "## 09:00: First touch",
      "The outreach agent drafts one message per contact per channel, referencing the brief. In the supervised phase, a human approves each; by month three, the agent sends autonomously for accounts below a risk threshold and queues the rest.",
      "## Throughout the day: Conversations",
      "Replies arrive. The conversation agent answers straightforward questions, shares proof, and handles common objections. Anything involving pricing, a competitor by name, or an emotional tone is escalated with the full thread to the client's SDR, who replies in a minute or two.",
      "## 16:00: Booking",
      "Three prospects agree to meet. The scheduling agent offers times, books into the rep's calendar and the CRM, sends the brief to the rep, and confirms with the prospect. The rep's only job tomorrow is to turn up prepared.",
      "## 18:00: Report",
      "Accounts engaged, replies, escalations handled, meetings booked, and what the agents learned. A human reads it in three minutes. That is the day. It is not magic; it is a very disciplined SDR team that never gets bored.",
    ],
    related: ["build-vs-buy-gtm-ai-twin", "demand-generation-2026-what-changed"],
  },
  {
    slug: "build-vs-buy-gtm-ai-twin",
    title: "Build, buy or twin: choosing an AI GTM approach",
    dek: "Subscribe to a tool, build your own agents, or have custom agents built and run for you. The trade-offs, without the vendor spin.",
    cluster: "ai-in-gtm",
    author: "kingshuk-hazra",
    date: "2026-08-20",
    body: [
      "Every B2B leader we speak to is being asked the same question by their board: what is our AI plan for pipeline? There are three honest answers, and the right one depends on what you have.",
      "## Buy a tool",
      "AI SDR products are real and improving. They suit companies with a clean ICP, a maintained database, a messaging system that already works and someone to operate the tool daily. If you have all four, a tool is the cheapest path. Most companies have one or two, and the tool becomes a very fast way to send bad messages to the wrong accounts.",
      "## Build your own",
      "Companies with an engineering team and GTM operations maturity can assemble agents from platforms and models. The advantages are control and data ownership. The cost is time: six to nine months to production in our experience, plus ongoing maintenance, plus the fact that the engineers building it have never booked a meeting.",
      "## Have a twin built",
      "The middle path is custom agents designed and run by people who know GTM, on a platform they control, handed over with the operating rhythm. This is what we do. It suits companies that want the economics of agents without the year of learning, and want to own the result at the end.",
      "## The question to ask any option",
      "Who decides which accounts deserve effort, and how did they learn? If the answer is 'the model', ask what it was trained on. If the answer is 'you', ask how much of your week that will take. The right approach is the one where judgement is designed in, not left to whoever is nearest the keyboard.",
    ],
    related: ["what-an-ai-sdr-does-all-day", "intent-data-is-not-a-list"],
  },
];

export function getInsight(slug: string) {
  return insights.find((i) => i.slug === slug);
}
export function getCluster(slug: string) {
  return clusters.find((c) => c.slug === slug);
}
export const insightsByDate = [...insights].sort((a, b) => (a.date < b.date ? 1 : -1));
