import type { Practice } from "./types";

export const practices: Practice[] = [
  {
    slug: "gtm-strategy",
    index: "01",
    name: "GTM Strategy & Positioning",
    short: "GTM Strategy",
    tagline: "Decide where to win before you spend a rupee winning it.",
    summary:
      "Market sizing, ICP definition, positioning, pricing and channel design for B2B technology companies entering a market, re-entering one, or resetting after growth stalled. The output is a plan your sales and marketing teams can actually run on Monday.",
    accent: "ember",
    services: [
      "GTM setup for a new market or product",
      "Repositioning after a stall or pivot",
      "ICP and segment definition",
      "Market sizing, forecasting & scenario planning",
      "Pricing and packaging design",
      "India entry for global SaaS",
      "Founder & CEO positioning",
    ],
    problem: {
      title: "Most GTM plans are a list of channels, not a set of decisions.",
      points: [
        "The ICP is a firmographic filter, so every campaign talks to a segment that never buys.",
        "Positioning was written by product, so it describes features and never names a category or an enemy.",
        "The forecast is a spreadsheet of hope, so the board discovers the miss two quarters late.",
      ],
    },
    deliverables: [
      { title: "Market map & sizing", body: "TAM/SAM/SOM built bottom-up from account counts, not analyst percentages, with three demand scenarios." },
      { title: "ICP & buying-group definition", body: "Who buys, who blocks, what triggers a purchase, and what a disqualifying account looks like." },
      { title: "Positioning & narrative", body: "Category, alternative, unique capability, proof — written as a one-page narrative your CEO can say out loud." },
      { title: "Pricing & packaging", body: "Tiers, metrics and anchors tested against willingness-to-pay interviews with real buyers." },
      { title: "Channel & motion design", body: "Which mix of outbound, inbound, partner and product-led you can afford, in what order, with what headcount." },
      { title: "The 90-day operating plan", body: "Owners, budget, targets and weekly rituals. This is the part most strategy decks leave out." },
    ],
    process: [
      { phase: "01", title: "Diagnose", body: "Pipeline archaeology: we read every closed-won and closed-lost deal from the last eighteen months, interview customers and lost prospects, and audit the current motion.", duration: "2 weeks" },
      { phase: "02", title: "Decide", body: "Segments, positioning, pricing and channel mix, argued through with the founders in two working sessions. We bring the data; you bring the ambition.", duration: "2 weeks" },
      { phase: "03", title: "Document", body: "The narrative, the plan, the numbers and the enablement kit for the team, written to be used, not filed.", duration: "1 week" },
      { phase: "04", title: "Deploy", body: "Optional: we stay on to run the first ninety days through our Demand Generation practice or hand over to your team with weekly reviews.", duration: "90 days" },
    ],
    sampleOutput: {
      kind: "Positioning narrative · excerpt",
      title: "ICP tier 1 — extract from a client narrative",
      lines: [
        "FOR      mid-market SaaS companies (200–1,500 staff) selling into regulated industries",
        "WHO      have outgrown spreadsheet-based vendor risk reviews",
        "WE ARE   the vendor-assurance layer, not another GRC suite",
        "UNLIKE   [[Vanta-style]] compliance automation, which stops at your own controls",
        "WE       continuously monitor the vendors your auditors will ask about",
        "PROOF    [[closes 61% faster]] on enterprise security questionnaires (client data)",
        "TRIGGER  first enterprise deal blocked by procurement · SOC 2 renewal · new CISO",
      ],
    },
    outcomes: [
      { value: "[[6 wks]]", label: "from kickoff to a board-approved plan" },
      { value: "[[2.4×]]", label: "average win-rate improvement after repositioning" },
      { value: "[[31]]", label: "GTM strategies delivered since 2018" },
    ],
    pricing: {
      model: "Fixed-fee diagnostic, then a fixed-fee strategy sprint.",
      from: "[[₹6.5 L / $8k]]",
      note: "Diagnostic-only engagements available. Strategy sprint fee is credited against the first quarter of any Demand Generation retainer.",
    },
    faq: [
      { q: "How is this different from a management consultancy's GTM deck?", a: "We have run the motions we recommend. Every plan includes the operating rhythm, headcount and budget to execute it, and we can stay to run it. Consultancies leave at the deck." },
      { q: "Do you work with pre-revenue companies?", a: "Rarely. Our best work needs at least a handful of paying customers to learn from. If you are pre-revenue we will say so on the first call and point you to a cheaper path." },
      { q: "Can you help a global SaaS company enter India?", a: "Yes, and it is one of our most requested engagements: the founders led India marketing for AWS and other global vendors, so we know which playbooks transfer and which do not." },
      { q: "What do you need from us?", a: "Access to your CRM, ten hours of founder time across six weeks, and introductions to five customers and five lost prospects." },
    ],
    relatedWork: ["cloud-partner-india-entry", "devtools-outbound-engine"],
  },
  {
    slug: "demand-generation",
    index: "02",
    name: "Demand Generation",
    short: "Demand Gen",
    tagline: "An outsourced pipeline team that is accountable for meetings, not activity.",
    summary:
      "Account-based marketing, social selling, content, events and outbound run as one programme by a pod that reports weekly on qualified pipeline. Productised formats — Lead Generation in a Box, Webinar-as-a-Service, Quiz-as-a-Service — for companies that need a specific motion stood up fast.",
    accent: "ember",
    services: [
      "Account-Based Marketing (incl. Event ABM)",
      "Social selling on LinkedIn",
      "Outbound sequencing & messaging",
      "Content strategy & technical writing",
      "Webinar-as-a-Service",
      "Quiz-as-a-Service",
      "Third-party event lead generation",
      "Product Marketing-as-a-Service",
      "Lead Generation in a Box",
    ],
    problem: {
      title: "Activity is easy to buy. Pipeline is not.",
      points: [
        "Agencies report opens, clicks and MQLs because nobody made them own the meeting.",
        "Outbound, content and events are run by three different vendors who have never met.",
        "Your best-fit accounts get the same sequence as everybody else, so they ignore it like everybody else.",
      ],
    },
    deliverables: [
      { title: "Target account universe", body: "A ranked, refreshed list of accounts and buying-group contacts, built by our Revenue Intelligence practice and scored on fit and intent." },
      { title: "Messaging system", body: "Persona-level value propositions, objection handling and a sequence library, written from customer interviews and tested weekly." },
      { title: "Multi-channel programme", body: "Outbound email and LinkedIn, social selling from your leaders' profiles, content, and events, orchestrated on one calendar." },
      { title: "Productised formats", body: "Webinar-as-a-Service, Quiz-as-a-Service and Event ABM: we handle audience acquisition, content, hosting and the post-event database." },
      { title: "Weekly pipeline review", body: "One page: accounts engaged, meetings booked, meetings held, opportunities created, what we are changing next week." },
      { title: "Sales handover kit", body: "Every meeting arrives with account research, the thread that got it, and a suggested agenda." },
    ],
    process: [
      { phase: "01", title: "Foundation", body: "ICP, universe, messaging and tooling. We plug into your CRM and sequencing stack or bring ours.", duration: "3 weeks" },
      { phase: "02", title: "Launch", body: "First sequences and social-selling cadence live. Expect learning, not volume; we optimise on reply quality before scale.", duration: "4 weeks" },
      { phase: "03", title: "Scale", body: "Winning messages scaled, content and events layered in, ABM plays for tier-1 accounts.", duration: "Month 3 →" },
      { phase: "04", title: "Compound", body: "By month six the programme runs on institutional knowledge: what works for which segment, documented and reusable.", duration: "Ongoing" },
    ],
    sampleOutput: {
      kind: "Outbound sequence · step 1 of 6",
      title: "Persona: VP Engineering, Series-B DevTools",
      lines: [
        "SUBJECT  your flaky test budget",
        "",
        "Priya — saw the [[Acme]] eng blog on splitting the monorepo.",
        "Teams that do that usually see CI flake rates jump for a quarter",
        "while ownership settles. Two of your peers ([[names]] on request)",
        "cut retries 40% by quarantining flaky suites automatically.",
        "",
        "Worth 20 minutes to compare notes on how they did it? Either way,",
        "happy to send the write-up.",
        "",
        "— Kingshuk · LeadStrategus for [[Client]]",
      ],
    },
    outcomes: [
      { value: "[[20+]]", label: "qualified meetings per quarter is our typical mid-market baseline" },
      { value: "[[38%]]", label: "meeting-to-opportunity conversion across programmes" },
      { value: "[[6 mo]]", label: "median client tenure is over two years" },
    ],
    pricing: {
      model: "Monthly retainer for a pod, scoped to a meetings target.",
      from: "[[₹3.5 L / $4.2k per month]]",
      note: "Productised formats (Webinar-as-a-Service, Quiz-as-a-Service, Lead Generation in a Box) are priced per programme. Three-month minimum.",
    },
    faq: [
      { q: "Do you guarantee meetings?", a: "We commit to a target and we report against it every week. If we miss it two months running we will tell you why and what changes, or we will end the engagement. We do not sell pay-per-meeting because it produces bad meetings." },
      { q: "Whose tools do you use?", a: "Yours if you have them: HubSpot, Salesforce, Apollo, Clay, LinkedIn Sales Navigator, Smartlead and similar are all familiar. If you do not, we run the programme on our stack and hand it over at the end." },
      { q: "Will you send from our domain?", a: "We set up and warm dedicated sending domains so your primary domain's reputation is never at risk. Social selling always runs from your leaders' real profiles, with their approval on every post." },
      { q: "What is Lead Generation in a Box?", a: "A fixed-scope, fixed-price programme for one segment: universe, messaging, six-week outbound and social campaign, and a handover. It exists for companies that need to prove a motion before funding a retainer." },
    ],
    relatedWork: ["devtools-outbound-engine", "healthcare-social-selling", "docsoft-enterprise-abm", "testing-webinar-series"],
  },
  {
    slug: "revenue-intelligence",
    index: "03",
    name: "Revenue Intelligence",
    short: "Intelligence",
    tagline: "Know which accounts are in-market this quarter, and why.",
    summary:
      "Database-as-a-Service, intent-based account intelligence, open-source intelligence (OSINT) and market research delivered as living datasets, not one-off reports. This practice feeds every other one: the right accounts, the right people, the right moment.",
    accent: "ember",
    services: [
      "Database-as-a-Service",
      "Intent-based account intelligence",
      "Open-source intelligence (OSINT) for sales",
      "Market research, forecasting & scenario planning",
      "Competitive intelligence",
      "Account and buying-group mapping",
    ],
    problem: {
      title: "You are paying for data that is wrong, stale, and the same as your competitor's.",
      points: [
        "Purchased lists decay [[2–3% a month]] and nobody owns keeping them alive.",
        "Intent vendors show you the same surge topics they show everyone, with no link to your ICP.",
        "The signals that actually predict a deal, such as a new CISO, a funding round, a job post, a tech migration, sit in public sources nobody is reading.",
      ],
    },
    deliverables: [
      { title: "Living account universe", body: "Your total addressable accounts, deduplicated against CRM, enriched and re-verified on a schedule you choose." },
      { title: "Buying-group maps", body: "Every named account with its economic buyer, champion, blockers and influencers, with verified contact routes." },
      { title: "Intent & trigger feed", body: "Weekly ranked list of accounts showing buying signals, with the evidence and a suggested first message." },
      { title: "OSINT briefs", body: "Deep account research on demand: org changes, tech stack, hiring, financials, public commitments, executive priorities." },
      { title: "Market research & forecasting", body: "Bottom-up sizing, demand scenarios and competitive landscapes for board decks, fundraising or market entry." },
      { title: "CRM hygiene", body: "Duplicates, decay and gaps fixed at source, so sales stops fighting the database." },
    ],
    process: [
      { phase: "01", title: "Define", body: "ICP, signal taxonomy and the definition of a qualified account, agreed with sales leadership.", duration: "1 week" },
      { phase: "02", title: "Build", body: "Universe assembled from twenty-plus sources, deduplicated, verified and loaded into your CRM.", duration: "2–3 weeks" },
      { phase: "03", title: "Enrich", body: "Buying groups mapped, intent and OSINT monitoring switched on, first weekly feed delivered.", duration: "2 weeks" },
      { phase: "04", title: "Maintain", body: "Monthly re-verification, quarterly universe refresh, feed tuned on what sales actually converted.", duration: "Ongoing" },
    ],
    sampleOutput: {
      kind: "Intent feed · one row",
      title: "Account brief: [[Northwind Logistics]] · score 87",
      lines: [
        "FIT       ICP tier 1 · 1,200 staff · SAP S/4 migration announced Q2",
        "SIGNALS   3 open roles: 'Integration Architect' (posted 9d ago)",
        "          New CIO ([[ex-Maersk]]) started 6 weeks ago",
        "          G2 category page views ↑ 4× vs 90-day baseline",
        "PEOPLE    CIO · VP Apps · Head of Integration (all verified)",
        "OPENER    Congratulate CIO on appointment; reference S/4 timeline;",
        "          offer the integration-risk checklist from [[Client]]'s blog",
        "NEXT      Sequence 'S4-Migration-v3' · owner: AE-North",
      ],
    },
    outcomes: [
      { value: "[[94%]]", label: "contact accuracy on delivery, re-verified monthly" },
      { value: "[[3×]]", label: "reply rate on signal-triggered outreach vs. list-based" },
      { value: "[[20+]]", label: "sources combined into each account universe" },
    ],
    pricing: {
      model: "Per-account-universe build fee, then a monthly maintenance and intelligence subscription.",
      from: "[[₹1.8 L / $2.2k]]",
      note: "OSINT briefs and market research are scoped per project. Existing Demand Generation clients receive this practice inside their retainer.",
    },
    faq: [
      { q: "Is this compliant with GDPR and India's DPDP Act?", a: "Yes. We source from public and licensed data, record lawful basis per record, honour suppression lists and do not process special-category data. We will happily walk your DPO through the pipeline." },
      { q: "Which intent data providers do you use?", a: "We combine third-party intent with first-party (your web and content engagement) and public triggers we monitor ourselves. The ranking model is tuned to your closed-won history, which is why it stops looking like everybody else's feed." },
      { q: "Can you just sell us a list?", a: "We can, and Database-as-a-Service starts there, but a list without a maintenance plan is worth about half its price in six months. We will tell you that on the call." },
      { q: "How do OSINT briefs differ from what my reps can Google?", a: "Depth, structure and time. A brief takes an analyst three to four hours across filings, hiring data, tech-stack detection, executive interviews and social. Reps have fifteen minutes." },
    ],
    relatedWork: ["mediatech-expansion-intel", "devtools-outbound-engine"],
  },
  {
    slug: "enablement",
    index: "04",
    name: "Sales & Marketing Enablement",
    short: "Enablement",
    tagline: "Make the team you already have run like the one you wish you had.",
    summary:
      "Training, coaching and change management for B2B sales and marketing teams, delivered by people who have led those teams at AWS, Gartner and SAP. Programmes for founders selling for the first time, marketing teams moving from brand to pipeline, and sales teams adopting AI tooling.",
    accent: "ember",
    services: [
      "Sales coaching for founders and first sales hires",
      "Marketing excellence & pipeline-marketing training",
      "Social selling training for leadership teams",
      "AI-in-GTM adoption programmes",
      "Change management for new GTM motions",
      "Founder & CEO personal branding",
    ],
    problem: {
      title: "You hired well. Then you gave them a deck and hoped.",
      points: [
        "Founders carry every deal because nobody has codified how they sell.",
        "Marketing measures brand because nobody taught it to own pipeline.",
        "The new tools were bought, not adopted; three months later, usage is at [[11%]].",
      ],
    },
    deliverables: [
      { title: "Sales playbook", body: "Your ICP, discovery framework, demo narrative, objection library and deal-review cadence, written from how your best deals actually closed." },
      { title: "Cohort training", body: "Six-to-twelve-week programmes with live sessions, deal clinics and homework on real pipeline. No role-plays about widgets." },
      { title: "1:1 coaching", body: "Fortnightly coaching for founders, first sales hires and marketing leads, with a shared scorecard." },
      { title: "Marketing operating system", body: "Planning cadence, pipeline metrics, campaign templates and a content engine the team can run without an agency." },
      { title: "AI adoption programme", body: "Tool selection, prompts and workflows, guard-rails, and the habit-building that makes AI stick in a sales team." },
      { title: "Executive presence", body: "Personal branding and social-selling programmes for founders and CXOs, including ghost-writing with their approval." },
    ],
    process: [
      { phase: "01", title: "Assess", body: "Ride-alongs, call reviews, pipeline analysis and a skills baseline for every participant.", duration: "2 weeks" },
      { phase: "02", title: "Design", body: "Curriculum built around the three behaviours that would most change your numbers, not a generic syllabus.", duration: "1 week" },
      { phase: "03", title: "Run", body: "Weekly live sessions, deal clinics and coaching, with managers trained to coach so it survives our exit.", duration: "6–12 weeks" },
      { phase: "04", title: "Embed", body: "Scorecards, rituals and a ninety-day reinforcement plan owned by your managers.", duration: "90 days" },
    ],
    sampleOutput: {
      kind: "Curriculum · founder sales cohort",
      title: "Twelve weeks, one hour live per week",
      lines: [
        "W01  Why they buy: ICP, triggers and the cost of doing nothing",
        "W02  Discovery that qualifies out, fast",
        "W03  The demo is a story, not a tour",
        "W04  Deal clinic #1 (live pipeline)",
        "W05  Multi-threading a buying group",
        "W06  Pricing conversations without discounting",
        "W07  Deal clinic #2",
        "W08  Social selling from a founder's profile",
        "W09  Using AI research agents without losing the thread",
        "W10  Deal clinic #3",
        "W11  Forecasting you can defend",
        "W12  Hiring and onboarding your first AE",
      ],
    },
    outcomes: [
      { value: "[[41%]]", label: "average lift in stage-2 conversion after a cohort" },
      { value: "[[600+]]", label: "sales and marketing professionals trained" },
      { value: "[[9/10]]", label: "median participant rating across programmes" },
    ],
    pricing: {
      model: "Per-cohort fee for training; monthly for coaching.",
      from: "[[₹2.4 L / $2.9k per cohort]]",
      note: "Founder coaching and executive branding are scoped individually. Corporate cohorts of ten-plus receive playbook development included.",
    },
    faq: [
      { q: "Is this classroom sales training?", a: "No. Every session works on live deals and real pipeline. Participants leave each week with something changed in the CRM, not a certificate." },
      { q: "Who delivers it?", a: "The founders and a small bench of senior operators. Nobody who teaches for us has less than fifteen years of quota-carrying or pipeline-owning experience." },
      { q: "Can you train our team on AI tools?", a: "Yes. Our AI-in-GTM programme covers research agents, writing assistants and sequencing automation, with the guard-rails that stop teams sending embarrassing things at scale." },
      { q: "Do you do personal branding for founders?", a: "We do, with a rule: nothing is published without the founder's approval and the ideas have to be theirs. We provide the structure, the cadence and the editing." },
    ],
    relatedWork: ["healthcare-social-selling", "cloud-partner-india-entry"],
  },
];

export function getPractice(slug: string) {
  return practices.find((p) => p.slug === slug);
}
