import type { CaseStudy } from "./types";

/**
 * SAMPLE CASE STUDIES. Every entry here is a placeholder.
 *
 * They exist so each service page can show its case-study section in the
 * shape it will have, and so that section links somewhere real. None of them
 * describes an actual client: the client is an anonymous descriptor, every
 * figure is a [[placeholder]], and each page and card carries a visible
 * "Sample case study" label. The master portfolio is explicit that proof gaps
 * must not be filled with invented metrics, and these must not be read as
 * proof.
 *
 * Replacing one: keep its slug if you can (links already point at it), set
 * `sample: false`, name the client if they have agreed to it, and replace the
 * [[figures]] with the signed-off ones. The document's case-study library
 * lists the real engagements that should take these places (Dover, Alibaba
 * Cloud, Indus Net Technologies, Ernst & Young, Stibo Systems, Speridian,
 * SOA IT Solutions, Retigence, AskMeIdentity, BSMA Summit 2024).
 *
 * Shape follows the document's case-study page format:
 *   Situation → Question → What LeadStrategus did → Evidence / deliverables
 *   → Outcome → What changed in the client's GTM motion.
 *
 * `services` decides which service pages show the case. Every service has at
 * least two; scripts/content/check-cases.mjs fails the build check otherwise.
 */
export const caseStudies: CaseStudy[] = [
  {
    slug: "cloud-partner-india-entry",
    sample: true,
    client: "A global cloud software vendor",
    vertical: "Cloud & Infrastructure",
    region: "India & Southeast Asia",
    group: "gtm-strategy",
    services: ["gtm-setup", "market-intelligence", "research-and-forecasting", "scenario-planning", "account-prospect-intelligence", "channel-strategy"],
    title: "Choosing the first market, the first segment and the order to enter them",
    summary: "A vendor with a strong product and no regional plan needed to decide where to start before it hired a single seller.",
    stats: [
      { value: "[[3]]", label: "markets assessed" },
      { value: "[[120]]", label: "target companies mapped" },
      { value: "[[2]]", label: "scenarios carried to the board" },
    ],
    situation: "The vendor had grown in North America and Europe and was being asked by its board for a plan for India and Southeast Asia. Inbound interest from the region was real but scattered, and nobody could say which segment would pay first.",
    question: "Which market and which segment should come first, what should the route to market be, and what would it cost to find out the hard way if the answer were wrong?",
    whatWeDid: [
      "Reconstructed each candidate market bottom-up from company counts rather than analyst totals.",
      "Defined the ICP and the buying group, including the accounts to disqualify.",
      "Compared direct, partner-led and hybrid routes against the vendor's budget and headcount.",
      "Built two forward scenarios with the decision gates that would move the plan from one to the other.",
    ],
    evidence: [
      "Market map and sizing model for each candidate market",
      "ICP definition with disqualifiers",
      "Route-to-market comparison",
      "Scenario plan with decision gates and a 90-day operating plan",
    ],
    outcome: "The board approved a single-market entry with a partner-led route, a target list of [[120]] companies and a review gate at [[two]] quarters.",
    whatChanged: "Regional growth stopped being a reaction to inbound enquiries and became a sequenced plan with owners, gates and a number to hit.",
    tags: ["GTM setup", "Market entry", "Scenario planning"],
    featured: false,
    year: "[[2025]]",
  },
  {
    slug: "repositioning-stalled-growth",
    sample: true,
    client: "A data platform company",
    vertical: "SaaS",
    region: "United States",
    group: "gtm-strategy",
    services: ["repositioning", "product-marketing-as-a-service", "sales-deck", "pitch-deck", "sales-marketing-consulting"],
    title: "Rebuilding the market story after the category moved underneath it",
    summary: "A product that used to sell on features was losing deals to a category its buyers now described in different words.",
    stats: [
      { value: "[[24]]", label: "buyer interviews" },
      { value: "[[1]]", label: "narrative across every deck" },
      { value: "[[31%]]", label: "lift in stage-two conversion" },
    ],
    situation: "Win rates had fallen for three quarters. The product had not got worse; the buyers had started evaluating it against a newer category, and the company's story still described the old one.",
    question: "What does the buyer now need, and which part of that can this company credibly own?",
    whatWeDid: [
      "Interviewed recent wins, losses and churned customers about how they framed the problem.",
      "Mapped the competitive frame the buyer was actually using.",
      "Chose a new position and wrote the narrative, then rebuilt the pitch and sales decks on it.",
      "Briefed sales and marketing together so the story changed everywhere at once.",
    ],
    evidence: [
      "Buyer and competitive evidence pack",
      "Positioning narrative",
      "Rebuilt pitch deck and sales deck system",
      "Message guide for sales and marketing",
    ],
    outcome: "Stage-two conversion rose by [[31%]] in the following [[two]] quarters, and the sales cycle shortened by [[18]] days.",
    whatChanged: "Sales stopped explaining the product and started talking about the buyer's problem in the buyer's words.",
    tags: ["Repositioning", "Product marketing", "Sales deck"],
    featured: false,
    year: "[[2025]]",
  },
  {
    slug: "founder-voice-cybersecurity",
    sample: true,
    client: "A founder-led cybersecurity company",
    vertical: "Cybersecurity",
    region: "India & Middle East",
    group: "gtm-strategy",
    services: ["founder-brand", "sales-messaging", "content-marketing", "social-selling", "webinar-as-a-service"],
    title: "Turning a founder's expertise into a reason for buyers to start the conversation",
    summary: "The founder was the company's best salesperson and its least visible asset.",
    stats: [
      { value: "[[40]]", label: "pieces published in a quarter" },
      { value: "[[3.4×]]", label: "growth in executive followers" },
      { value: "[[17]]", label: "conversations started from content" },
    ],
    situation: "Every large deal the company had won started with a conversation with its founder. Outside those conversations, the market had no idea what the founder thought.",
    question: "What point of view could the founder own, and how could it reach the buyers who mattered without becoming a content treadmill?",
    whatWeDid: [
      "Found the three positions the founder held that the market was not hearing from anyone else.",
      "Built an editorial system around them, written in the founder's voice.",
      "Connected the content to sales messaging so a post could start a conversation a rep could continue.",
      "Ran a webinar series with the founder as the lead voice.",
    ],
    evidence: [
      "Executive point-of-view document",
      "Editorial calendar and content system",
      "Message sequences tied to each theme",
    ],
    outcome: "[[17]] sales conversations in the first quarter began with a buyer responding to the founder's content.",
    whatChanged: "The founder's thinking became something the sales team could use, not something only the founder could deliver.",
    tags: ["Founder branding", "Thought leadership"],
    featured: false,
    year: "[[2025]]",
  },
  {
    slug: "mediatech-expansion-intel",
    sample: true,
    client: "A professional services firm",
    vertical: "Media Technology",
    region: "United Kingdom & Europe",
    group: "gtm-strategy",
    services: ["research-and-forecasting", "market-intelligence", "content-marketing", "sales-messaging"],
    title: "A primary research study the market wanted to read",
    summary: "Original research turned into a market-facing report, and the report turned into conversations.",
    stats: [
      { value: "[[1,200]]", label: "survey respondents" },
      { value: "[[30]]", label: "executive interviews" },
      { value: "[[1]]", label: "market-facing report" },
    ],
    situation: "The firm wanted to be seen as the authority on a fast-moving topic in its sector, and its existing content repeated what everyone else was saying.",
    question: "What could the firm know that nobody else did, and how could that become a story the market would want to read?",
    whatWeDid: [
      "Designed a survey and an executive interview programme.",
      "Ran the analysis and found the findings that contradicted common assumptions.",
      "Storyboarded the report and the content that would carry it.",
    ],
    evidence: [
      "Survey design and fieldwork",
      "Interview programme and analysis",
      "Storyboard and final market-facing report",
    ],
    outcome: "The report was cited in [[12]] trade publications and generated [[60]] qualified enquiries in its first [[three]] months.",
    whatChanged: "The firm went into sales conversations with evidence the buyer had not seen, rather than claims the buyer had heard before.",
    tags: ["Research", "Revenue content"],
    featured: false,
    year: "[[2024]]",
  },
  {
    slug: "docsoft-enterprise-abm",
    sample: true,
    client: "A document software vendor",
    vertical: "Document Software",
    region: "United Kingdom & Europe",
    group: "account-intelligence",
    services: ["account-prospect-intelligence", "intent-account-intelligence", "osint-for-sales", "account-based-marketing"],
    title: "An account universe the sales team could actually sell into",
    summary: "A purchased list was replaced by a researched, maintained universe of accounts and buyers.",
    stats: [
      { value: "[[220]]", label: "target accounts" },
      { value: "[[640]]", label: "verified buyers" },
      { value: "[[14]]", label: "accounts showing buying signals" },
    ],
    situation: "The team had a large purchased database and a small pipeline. Most of the records were out of date, and nobody could say which accounts were worth attention this quarter.",
    question: "Which accounts fit, which of them are worth attention now, and who inside them should we speak to?",
    whatWeDid: [
      "Rebuilt the target universe from the ICP outward and verified the buyers in each account.",
      "Researched competitor-user accounts and public buying signals.",
      "Turned the signals into account briefs a rep could act on.",
    ],
    evidence: [
      "Account and buyer universe, verified",
      "Competitor-user and buying-signal research",
      "Account briefs for priority accounts",
    ],
    outcome: "[[14]] accounts were moved into active pursuit in the first month, and [[9]] of them accepted a first meeting.",
    whatChanged: "Prioritisation moved from fit alone to fit plus timing, so effort went to accounts worth attention now.",
    tags: ["Account intelligence", "OSINT", "ABM"],
    featured: true,
    year: "[[2025]]",
  },
  {
    slug: "healthcare-social-selling",
    sample: true,
    client: "A healthcare IT provider",
    vertical: "Healthcare IT",
    region: "India & Middle East",
    group: "demand-generation",
    services: ["account-based-marketing", "social-selling", "intent-account-intelligence", "osint-for-sales", "founder-brand"],
    title: "Opening a new geography through the people who decide",
    summary: "Research-led ABM and executive social engagement opened conversations that cold calling never had.",
    stats: [
      { value: "[[22]]", label: "qualified leads" },
      { value: "[[19]]", label: "meetings in four months" },
      { value: "[[6]]", label: "CXO relationships" },
    ],
    situation: "The provider was entering a new geography where its name meant nothing and hospital decision makers did not take calls from vendors they did not know.",
    question: "How do you reach a small number of senior buyers who do not respond to outreach, without waiting years for a reputation?",
    whatWeDid: [
      "Selected target accounts and mapped the buying group in each.",
      "Researched each account's priorities from public sources.",
      "Ran personalised engagement through the executives' own social presence.",
    ],
    evidence: [
      "Target account list and buying-group maps",
      "Account research briefs",
      "Personalised message sequences and social engagement plan",
    ],
    outcome: "[[22]] qualified leads and [[19]] meetings in [[four]] months, with relationships established at [[six]] CXO-level contacts.",
    whatChanged: "The company entered the market through relationships rather than through a cold channel.",
    tags: ["ABM", "Social selling", "Healthcare"],
    featured: true,
    year: "[[2024]]",
  },
  {
    slug: "it-services-social-selling",
    sample: true,
    client: "An IT services company",
    vertical: "IT Services",
    region: "United States",
    group: "demand-generation",
    services: ["social-selling", "lead-generation-in-a-box", "inside-sales-setup", "digital-only-sales-funnel"],
    title: "LinkedIn conversations that turned into meeting interest",
    summary: "A connection-first social selling programme replaced interruption-led outreach.",
    stats: [
      { value: "[[1,800]]", label: "connection requests" },
      { value: "[[26%]]", label: "connection rate" },
      { value: "[[70]]", label: "deep conversations" },
    ],
    situation: "Cold email had stopped working for the company and its sellers had no other way to start conversations with the buyers they wanted.",
    question: "Can relationships be built at scale before asking for the meeting, and can that be run without hiring a team?",
    whatWeDid: [
      "Defined the target personas and the reasons each would want to talk.",
      "Rebuilt the sellers' profiles around the buyer's problem.",
      "Ran connection-first sequences that led with help, not a pitch.",
      "Handed warm conversations to an inside sales layer for follow-up.",
    ],
    evidence: [
      "Persona and message framework",
      "Profile rebuilds for each seller",
      "Social selling sequences and conversation playbook",
    ],
    outcome: "A [[26%]] connection rate, around [[70]] deep conversations and [[40%]] of them converted to meeting interest.",
    whatChanged: "The sellers had a repeatable way to start conversations that did not depend on interrupting anyone.",
    tags: ["Social selling", "Inside sales"],
    featured: false,
    year: "[[2024]]",
  },
  {
    slug: "devtools-outbound-engine",
    sample: true,
    client: "A developer tools company",
    vertical: "DevTools / SaaS",
    region: "United States",
    group: "demand-generation",
    services: ["lead-generation-in-a-box", "digital-only-sales-funnel", "product-marketing-as-a-service", "revenue-operations", "quiz-as-a-service"],
    title: "A complete pipeline motion without building the whole team",
    summary: "Managed demand generation plugged in the missing parts of the pipeline engine.",
    stats: [
      { value: "[[23]]", label: "qualified meetings in quarter one" },
      { value: "[[41%]]", label: "meeting-to-opportunity" },
      { value: "[[$1.9M]]", label: "pipeline created in six months" },
    ],
    situation: "The company had product-led adoption but no outbound motion, no product marketing function and no reporting that connected activity to pipeline.",
    question: "How do you add a full pipeline motion in one quarter without hiring a team to run it?",
    whatWeDid: [
      "Built the target universe and the messaging for each persona.",
      "Set up a buyer-first digital funnel alongside a managed outbound pod.",
      "Instrumented the motion so every stage was measured weekly.",
      "Used an interactive quiz as the entry point to the digital funnel.",
    ],
    evidence: [
      "Target universe and persona messaging",
      "Digital funnel and outbound sequences",
      "Weekly pipeline reporting",
    ],
    outcome: "[[23]] qualified meetings in the first quarter and [[$1.9M]] in pipeline within [[six]] months.",
    whatChanged: "Pipeline became a measured motion with weekly numbers rather than a by-product of product usage.",
    tags: ["Managed demand generation", "DevTools"],
    featured: true,
    year: "[[2025]]",
  },
  {
    slug: "sales-reset-scaleup",
    sample: true,
    client: "A B2B software scale-up",
    vertical: "SaaS",
    region: "India",
    group: "enablement",
    services: ["sales-marketing-consulting", "diagnostic-workshops", "coaching-and-training", "field-sales-enablement", "inside-sales-setup", "repositioning", "pitch-deck"],
    title: "Fixing the system around the sales team, not just the salespeople",
    summary: "A diagnostic found the constraint, and the reset fixed it rather than the symptom.",
    stats: [
      { value: "[[5]]", label: "new hires onboarded" },
      { value: "[[8]]", label: "weeks to first-quarter quota" },
      { value: "[[2×]]", label: "rep ramp speed" },
    ],
    situation: "Revenue had plateaued and leadership's first instinct was more sales training. The team was busy; the pipeline was not moving.",
    question: "Where is the real constraint in the system, and what would fixing it change?",
    whatWeDid: [
      "Ran diagnostic workshops across sales and marketing to find the bottleneck.",
      "Reset hiring, onboarding and knowledge transfer.",
      "Rebuilt pitching, content and message sequences.",
      "Coached the team until the new behaviour stuck.",
    ],
    evidence: [
      "Diagnostic findings and priority actions",
      "Hiring and onboarding programme",
      "Pitch, content and sequence library",
      "Coaching plan",
    ],
    outcome: "New sellers reached first-quarter quota in [[eight]] weeks instead of [[sixteen]].",
    whatChanged: "Sales and marketing ran on one system with one story, rather than two teams blaming each other for the pipeline.",
    tags: ["Sales reset", "Enablement"],
    featured: false,
    year: "[[2024]]",
  },
  {
    slug: "partner-route-to-market",
    sample: true,
    client: "An enterprise software vendor",
    vertical: "Software",
    region: "India & Southeast Asia",
    group: "enablement",
    services: ["channel-strategy", "field-sales-enablement", "coaching-and-training", "diagnostic-workshops", "scenario-planning", "gtm-setup", "sales-deck"],
    title: "Turning a list of partner logos into a route to market",
    summary: "The partner programme was redesigned around roles, segments and enablement.",
    stats: [
      { value: "[[40]]", label: "partners reviewed" },
      { value: "[[8]]", label: "partners kept as priority" },
      { value: "[[3×]]", label: "partner-sourced pipeline" },
    ],
    situation: "The vendor had signed dozens of partners and very few of them sold anything. Partner managers spent their time on the wrong ones.",
    question: "Which partners should play which role, in which segments, and what do they need from us to sell?",
    whatWeDid: [
      "Reviewed every partner against role, segment and capacity.",
      "Defined partner roles and the segments each would own.",
      "Built partner messaging and enablement, and trained the priority partners.",
    ],
    evidence: [
      "Partner assessment",
      "Channel strategy and partner role map",
      "Partner messaging and enablement kit",
    ],
    outcome: "Partner-sourced pipeline tripled within [[three]] quarters from [[eight]] priority partners.",
    whatChanged: "The channel became an intentional route to market rather than a collection of logos.",
    tags: ["Channel strategy", "Enablement"],
    featured: false,
    year: "[[2025]]",
  },
  {
    slug: "conference-pipeline-event-abm",
    sample: true,
    client: "An enterprise technology company",
    vertical: "Enterprise Software",
    region: "United States",
    group: "events",
    services: ["event-abm", "event-lead-generation", "custom-events", "buyer-matching", "meeting-intelligence", "event-discovery"],
    title: "A conference that produced meetings, not badge scans",
    summary: "Pre-event research and outreach turned an expensive sponsorship into a pipeline channel.",
    stats: [
      { value: "[[280]]", label: "target companies reached" },
      { value: "[[18]]", label: "meeting requests" },
      { value: "[[5×]]", label: "qualified meetings vs. attendance alone" },
    ],
    situation: "The company sponsored the same conference every year and came home with a stack of badge scans and no pipeline.",
    question: "Which attendees are worth meeting, and how do you get on their calendar before the event starts?",
    whatWeDid: [
      "Identified and researched the target accounts expected to attend.",
      "Ran pre-event outreach to book meetings in advance.",
      "Hosted a small invite-only session for the highest-value accounts.",
      "Briefed the team on every booked meeting and ran structured follow-up.",
      "Confirmed the ICP concentrated at this conference before committing the budget.",
    ],
    evidence: [
      "Attending-account research",
      "Pre-event outreach sequences",
      "Meeting briefs and follow-up plan",
    ],
    outcome: "[[18]] meeting requests from [[280]] companies reached, and [[five]] times more qualified meetings than attendance alone produced in prior years.",
    whatChanged: "Events stopped being a brand expense and became a planned pipeline channel.",
    tags: ["Event ABM", "Conferences"],
    featured: false,
    year: "[[2024]]",
  },
  {
    slug: "testing-webinar-series",
    sample: true,
    client: "A software testing company",
    vertical: "Software Testing / IT Services",
    region: "United States",
    group: "events",
    services: ["webinar-as-a-service", "quiz-as-a-service", "custom-events", "content-marketing"],
    title: "A webinar series treated as the middle of a demand programme",
    summary: "The audience, the content and the follow-up were built around each session.",
    stats: [
      { value: "[[6]]", label: "webinars in a series" },
      { value: "[[900]]", label: "registrations" },
      { value: "[[34]]", label: "sales conversations" },
    ],
    situation: "Previous webinars had drawn small audiences and ended with a recording nobody watched and no follow-up.",
    question: "How do you build an audience for a webinar and turn attendance into conversations?",
    whatWeDid: [
      "Planned a series around the questions target buyers were asking.",
      "Built the audience through partners, social and a pre-event quiz.",
      "Ran post-event sequences that continued the conversation.",
    ],
    evidence: [
      "Series plan and speaker briefs",
      "Audience-building plan and quiz",
      "Post-event follow-up sequences",
    ],
    outcome: "[[900]] registrations across [[six]] sessions and [[34]] sales conversations from the follow-up.",
    whatChanged: "Webinars became a programme with a before and an after, not a one-off broadcast.",
    tags: ["Webinars", "Quiz"],
    featured: false,
    year: "[[2024]]",
  },
  {
    slug: "ai-research-agent-pilot",
    sample: true,
    client: "A B2B services firm",
    vertical: "IT Services",
    region: "India",
    group: "leadstrategus-ai",
    services: ["ai-agent-build", "ai-demand-gen-system", "revenue-operations", "gtm-ai-twin"],
    title: "One agent for the workflow costing the team the most time",
    summary: "A single research agent took over account research, under human review.",
    stats: [
      { value: "[[1]]", label: "workflow automated" },
      { value: "[[12]]", label: "hours saved per rep, per week" },
      { value: "[[100%]]", label: "briefs reviewed by a person" },
    ],
    situation: "The team's sellers spent most of each week researching accounts before they could contact anyone.",
    question: "Which single workflow, if automated properly, would free the most time without lowering the quality of the work?",
    whatWeDid: [
      "Mapped the research workflow and the decisions inside it.",
      "Built and configured an agent on the firm's own logic and data.",
      "Kept a human review gate on every brief before it reached a seller.",
      "Designed the agent as the first component of a wider GTM AI Twin.",
    ],
    evidence: [
      "Workflow map",
      "Configured research agent",
      "Review and guardrail process",
    ],
    outcome: "Each seller recovered around [[12]] hours a week, with every brief still reviewed by a person.",
    whatChanged: "Research became something the team supervised rather than something it did by hand.",
    tags: ["AI agent", "Automation"],
    featured: false,
    year: "[[2025]]",
  },
  {
    slug: "gtm-ai-twin-rollout",
    sample: true,
    client: "A SaaS company",
    vertical: "SaaS",
    region: "United States",
    group: "leadstrategus-ai",
    services: ["gtm-ai-twin", "ai-demand-gen-system", "ai-agent-build"],
    title: "A GTM AI Twin configured on the company's own winning patterns",
    summary: "Connected agents ran the repeatable work, with judgement kept at the gates that mattered.",
    stats: [
      { value: "[[6]]", label: "weeks to a supervised live run" },
      { value: "[[7]]", label: "connected agents" },
      { value: "[[3]]", label: "human decision gates" },
    ],
    situation: "The company's best sellers knew exactly which accounts to pursue and what to say. That knowledge lived in their heads and did not scale.",
    question: "Can the context behind good demand-generation decisions be written into a system, without handing the decisions themselves to it?",
    whatWeDid: [
      "Captured the ICP, closed-won patterns, voice and qualification rules.",
      "Configured connected agents for discovery, signals, messaging and meetings.",
      "Set the decision gates where a person approves before anything goes out.",
    ],
    evidence: [
      "ICP and winning-pattern model",
      "Configured agent set",
      "Human decision gates and supervision plan",
    ],
    outcome: "A supervised live run in [[six]] weeks, with every outbound decision passing a human gate.",
    whatChanged: "The team's best practices became a system the whole team could run on.",
    tags: ["GTM AI Twin", "AI demand generation"],
    featured: false,
    year: "[[2025]]",
  },
  {
    slug: "expo-season-planning",
    sample: true,
    client: "An industrial technology company",
    vertical: "Industrial Technology",
    region: "Europe",
    group: "expotofunnel",
    services: ["event-discovery", "buyer-matching", "meeting-intelligence", "event-abm", "event-lead-generation"],
    title: "Choosing the shows because the buyers are there",
    summary: "A year of events was planned around where the ICP actually concentrates.",
    stats: [
      { value: "[[60]]", label: "shows assessed" },
      { value: "[[9]]", label: "shows kept" },
      { value: "[[2.5×]]", label: "meetings per event" },
    ],
    situation: "The company attended the same famous shows every year because it always had, with no evidence its buyers were there.",
    question: "Which shows does our ICP actually attend, and which buyers at them should we meet?",
    whatWeDid: [
      "Ranked candidate shows by ICP concentration rather than footfall.",
      "Matched each chosen show to the buyers worth meeting there.",
      "Prepared the team for every booked meeting and tracked follow-through.",
    ],
    evidence: [
      "Event ranking",
      "Buyer match lists per show",
      "Meeting briefs and follow-through tracking",
    ],
    outcome: "The event calendar shrank from [[fourteen]] shows to [[nine]] and meetings per event rose by [[2.5]] times.",
    whatChanged: "The events budget followed the buyers rather than the brand of the show.",
    tags: ["ExpoToFunnel", "Events"],
    featured: false,
    year: "[[2025]]",
  },
];

export const featuredCases = caseStudies.filter((c) => c.featured);
export const getCase = (slug: string) => caseStudies.find((c) => c.slug === slug);
export const casesFor = (serviceSlug: string) => caseStudies.filter((c) => c.services.includes(serviceSlug));
