// Generates PLACEHOLDERS.md: every [[flagged]] fact in /src/content and /src/app, by file.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
const roots = ["src/content", "src/app"];
const files = [];
const walk = (d) => { for (const f of readdirSync(d)) { const p = join(d, f); statSync(p).isDirectory() ? walk(p) : /\.(ts|tsx)$/.test(f) && files.push(p); } };
roots.forEach(walk);
let total = 0; const out = ["# Placeholders to verify before launch", "", "Every item below is an invented or unverified fact. It renders on the site with a dashed underline (toggle bottom-left). Replace the value in the named file, or remove the `[[ ]]` once verified.", "", "Generated by `npm run placeholders`.", ""];
for (const f of files.sort()) {
  const src = readFileSync(f, "utf8"); const lines = src.split("\n"); const hits = [];
  lines.forEach((l, i) => { for (const m of l.matchAll(/\[\[(.*?)\]\]/g)) hits.push({ line: i + 1, v: m[1] }); });
  if (!hits.length) continue; total += hits.length;
  out.push(`## ${f} (${hits.length})`, ""); hits.forEach((h) => out.push(`- L${h.line}: \`${h.v}\``)); out.push("");
}
out.splice(5, 0, `**Total: ${total}**`, "");
writeFileSync("PLACEHOLDERS.md", out.join("\n"));
console.log(`PLACEHOLDERS.md written · ${total} items across ${files.length} files scanned`);
